### ISSUE TITLE
Failed to load resource: the server responded with a status of 501 (Not Implemented)

### ISSUE THREAD

**Issue by sheetaldshivdas** [PredixDev/PredixMobileSDK#4]
OpenURL fails with the error "Failed to load resource: the server responded with a status of 501 (Not Implemented)" for all the api's be it tel, or email etc...

Using Predix container 2.3/3.0 same issue.

Below is the code:

```
 var pmurl = "http://pmapi/openurl";
    
        $.ajax({
            url: pmurl,
            type: "POST",
            data: JSON.stringify({
                "url": "mailto://sheetal.shivdas@ge.com?Subject=Hello%20Predix%20Email"
            }),
            success: function (result) {
                alert("success ");
            },
            error: function (e) {

                alert("error url ---> "+JSON.stringify(e));
            }
        });
```

**Comment by andyjohns** [comment]
OpenURL service must be registered in the Container.

**Comment by sheetaldshivdas** [comment]
Just like Camera Service, we add Camera "CameraService.self" for open URL what is supposed to be added?

**Comment by andyjohns** [comment]
OpenURLService

http://predixdev.github.io/PredixMobileSDK/iOS/Classes/OpenURLService.html
