### ISSUE TITLE
Not getting User Full Name or Profile Details.

### ISSUE THREAD

**Issue by sheetaldshivdas** [PredixDev/PredixMobileSDK#5]
I am using the api http://pmapi/user and http://pmapi/user/name, in a  Predix mobile app (hybrid), but in both the cases i only get SSO ID as username in return, can this be modified to get the SSO ID + user profile (like full name, email id, contact details etc...) are any configurations or settings missing from my end or is there any other alternate service to be called to get the desired information.

**Comment by andyjohns** [comment]
In the future, please ask questions in the Predix forums: https://forum.predix.io
You can find technical information about the User Information service in our wiki here: https://github.com/PredixDev/PredixMobileSDK/wiki/User-Information

The user information service returns whatever user information is gathered during the login process. In your example, it appears you're using a setup that has UAA integrated with GE's SSO system. In that case your user name is your GE SSO. In other cases the user name may be the email address of a UAA registration. User name is the login name of the user--what is entered on the login page. SSO integration generally does not return other user details at this time.
